### ISSUE TITLE
Add license + licensing notes

### ISSUE THREAD

**Issue by M-earnest** [azic0/pyTMST#1]
Great work so far! Minor but important note.

1. Please make sure to add a license file to the repository. The [TMST toolbox](https://github.com/LeoVarnet/TMST) references the CC-BY-NC-ND-4.0 (can be found here https://github.com/Gibberlings3/GitHub-Templates/blob/master/License-Templates/CC-BY-NC-ND-4.0/LICENSE-CC-BY-NC-ND-4.0.md).

2. Please add a note to the respective python scripts referencing said license + the original authors and packages (e.g. see https://github.com/LeoVarnet/TMST/blob/main/king2019_modfilterbank_updated.m).

**Comment by azic02** [comment]
Thanks for the note!

Turned out to be a bit of a hassle since we are not only porting [TMST](https://github.com/LeoVarnet/TMST/) but also relevant parts of [AMT](https://amtoolbox.org) and [LTFAT](https://ltfat.org) which are licensed differently. But I think I found a nice solution which has the side benefit of modularisation.
